### PR TITLE
Add new quick search feature.

### PR DESCRIPTION
**Pull request by egh**
Allows for quick search of an email archive.

### CODE REVIEW

**Comment by ikazuhiro** [comment]
Thank you for the suggestion.

1. Please specify authenticate method for gmail folder such as `"/x-gm-raw:\"%s\"/%%[Gmail]/All Mail:%s/clear@imap.gmail.com:993!"`.

2. When gmail language setting is different from English, folder name is also different from `All Mail`.  This part should be customizable or automatically set.

3. I wrote a patch to adjust `elmo-imap4-search-keys` automatically. Plase see https://gist.github.com/ikazuhiro/c43bb2a0978bd3ea28ab.

4. grep search needs that target directory is specified.  Fromat string for elmo-search folder name (currently `[\"%s\"]`) should be customizable or grep search can search without specifying target directory.

5. I think `imap` method of quicksearch is simply using filter feature, so it is not imap-specific.  This method should be renamed to such as `filter` method.

6. Please do not use `replace-regexp-in-string` directly.  Use `elmo-replace-in-string` (in `elmo-date.el`.  Its definition should be moved to `elmo-util.el`).

**Comment by egh** [comment]
Thank you so much for your suggestions. I will change the code to reflect these changes.

**Comment by egh** [comment]
I am looking at using RFC 6154 to autofind the gmail "all mail" folder. https://developers.google.com/gmail/imap_extensions?hl=en

I think this would be something useful for other Wanderlust features as well.

**Comment by egh** [comment]
I have completely reworked this feature to address your concerns and to make it fit better into the wanderlust system, using luna classes. The configuration has also been simplified - it now only requires a user to specify a `wl-quicksearch-folder`.

Thank you for all your feedback!

**Comment by egh** [comment]
Do you want me to incorporate that patch you made (https://gist.github.com/ikazuhiro/c43bb2a0978bd3ea28ab) into this pull request? Thanks!

**Comment by ikazuhiro** [comment]
I've merged your pull request with some modifications.
Thank you for your contribution.

**Comment by egh** [comment]
Thank you for your help with this, and thanks for merging!

**Pull request merged**
