### PR TITLE
fix closing parens position

### PR DESCRIPTION
**Pull request by conao3**
Fix closing parens position.
[Package-lint](https://github.com/purcell/package-lint) warns your package
> Closing parens should not be wrapped onto new lines. (emacs-lisp-package)

I eval below sexp in dired (depends `visual-regexp`).

``` emacs-lisp
(while (dired-get-filename nil 'no-error)
  (let ((file (dired-get-filename)))
    (with-temp-file file
      (insert-file-contents file)

      (while (not (= 0 (vr/replace "^(?!.*;)(.*)\\n[\\s\\t]*(\\)+)" "\\1\\2" (point-min) (point-max))))))
    (message file)
    (dired-next-line 1)))
```

### CODE REVIEW

**Comment by ikazuhiro** [comment]
Merged, thank you.
Please add ChangeLog entry at the next time.

**Comment by conao3** [comment]
Thanks.

OK, I'll add it next time. But, Is this kind of canned processing really necessary?
In the first time, a ChangeLog is pretty much the same format as what we get with a `git log`.
We can search for commits with changes in `git blame`, and since the project is already managed on GitHub, if we want more information, we can quickly find the PR where my changes were introduced.

**Comment by ikazuhiro** [comment]
I've obsolete ChangeLog files in Wanderlust, [APEL-LB](https://github.com/wanderlust/apel), [FLIM-LB](https://github.com/wanderlust/flim) and [SEMI-EPG](https://github.com/wanderlust/semi) repositories.  So you don't need ChangeLog entry, but please write commit messages as in Emacs's in the next time.

**Comment by conao3** [comment]
Thanks for a such great decision!
I'll write commit detail in the commit message in the next time.

**Pull request merged**
