### PR TITLE
elmo-rss.el

### PR DESCRIPTION
**Pull request by jech**
This is a trivial to use RSS/Atom/OPML backend for Wanderlust.  Unlike shimbun, it requires no configuration — just point it at a suitable feed, and it will do everything automatically:

    rss:https://github.com/wanderlust/wanderlust/commits/master.atom

It should handle all known feed types (two variants of Atom, three variants of RSS) except for binary-only Atom feeds.

Since it's a new backend, it shouldn't break anything.  I'm finding this extremely useful for tracking github/gitlab commits, and would appreciate if it could be merged.

@ikazuhiro, perhaps you could add Japanese documentation?

--jch

### CODE REVIEW

**Comment by jech** [comment]
> Please encode header strings.

Done.

> Please generate syntaxically valid message-id.

Any idea how to do that?  Is there any function in ELMO that I may reuse?

> elmo-rss-parse: Couldn't find Atom, RSS or OPML

That's because blogger returns a 302 redirect, and apparently `url-retrieve-synchronously` doesn't follow redirects.  I'll see how to fix that.

**Comment by jech** [comment]
> Please generate syntaxically valid message-id.

Done.

Kazuhiro-san, I'm not fixing the redirect issue — it looks to me like a bug in URL.  Please consider committing this.

**Comment by dmj** [comment]
I think there is nothing wrong with the redirect: http://www.blogger.com/feeds/8921458351195415378/posts/default/8493792679248392679 does not contain a feed but just a single Atom feed entry. That's why elmo-rss-parse complains.

**Comment by ikazuhiro** [comment]
Merged, thank you for your contribution.

**Comment by jech** [comment]
Merged.

**Pull request closed without merging**
